### ISSUE TITLE
How come that there will not be two threads modifying same parent?

### ISSUE THREAD

**Issue by UncP** [malbrain/Btree-source-code#2]
what if there are two childs modifying the same parent? since each child have a ParentModification lock, they can just lock it and modify their same parent at the same time.

**Comment by malbrain** [comment]
The parent modification lock allows a node to be unlocked before it's old fence key is deleted/changed and a new one added to its parent.  The problem is that if a second parent modification come, it needs to know the key it is looking for has already been posted.  The Parent-Modificaiton latch serializes these parent updates so that they occur in order in a high concurrency environment.  Other approaches keep a write lock on a node until after a fence key change is  posted to its parent.

**Comment by UncP** [comment]
Do you have a paper that explains this concurrent btree in detail?

**Comment by UncP** [comment]
I assume that you have read paper<<[Efficient Locking for Concurrent Operations on B-Trees](http://www.csd.uoc.gr/~hy460/pdf/p650-lehman.pdf)>> by Lehman and Yao. how come that there is no read lock in the algorithm?

**Comment by malbrain** [comment]
Yes, there is an informal paper at https://arxiv.org/pdf/1009.2764

The original paper by Lehman and Yao assumed that the btree pages would be read and written from a disk atomically by the operating system, so there wasn't a need for read locks.  This implementation uses memory mapping with direct-access to the page as a byte array, so it needs read locking.
